import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RecoilProvider from '../providers/RecoilProvider';
import GoogleOAuthProviderWrapper from "@/providers/GoogleAuthProviderWrapper";
import Header from "@/modules/user/layout/components/Header";
import ModalManager from "@/modules/user/layout/components/ModalManager";
import Script from 'next/script';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
     <head>
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="beforeInteractive"
        />
      </head>
    <RecoilProvider >
    <GoogleOAuthProviderWrapper>
      <ModalManager/>
      <body className={inter.className}>{children}</body>
      </GoogleOAuthProviderWrapper>
    </RecoilProvider>
    </html>
  );
}
